### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by Rishav2026** [20donkey/Term-project#3]
2 suggestions on content: 
1) Wrong spelling of sugar and spice on the 'other' page.
2) There is too much red empty space on the home page. 

2 Techincal suggestions:
1) On the home page instead of having just one still image where there is the start button. Have either a small video playing or changing images.
2) There is no hyperlink on 'Jade Garden' in the Chinese food section.

**Comment by 20donkey** [comment]
Hi, Thanks for your suggestions. 
For the hyperlink, not every restaurant has an official website so not all of them have a hyperlink.
