### ISSUE TITLE
Content Suggestions #1

### ISSUE THREAD

**Issue by lauraghouzi** [20donkey/Term-project#4]
https://github.com/20donkey/Term-project/blob/7464e28bc485f94cf27b6f552c479bad7dcbde45/index.html#L65-L88

I absolutely love the website, I think it's very clear and has a lot of fun content. One of the suggestions I have is if possible to change the font from your navigation bar and the rest of your website to the font of your logo.

**Comment by 20donkey** [comment]
The font of my logo is what I chose specifically for the logo. I tried it for the rest website but it doesn't look as clear and clean as the current one. still thanks!
