### ISSUE TITLE
Content Suggestions #2

### ISSUE THREAD

**Issue by lauraghouzi** [20donkey/Term-project#5]
https://github.com/20donkey/Term-project/blob/7464e28bc485f94cf27b6f552c479bad7dcbde45/recipe.html#L111-L127

Love this page, really like what you did with the ingredients button so it does not overcrowd the page. I would just space out the ingredients so its more clear, maybe make it in a list so it looks clearer.

**Comment by 20donkey** [comment]
I tried to make it in a list but it will look too long. I will try to add more space. Thanks!
