### ISSUE TITLE
Technical Suggestion #2

### ISSUE THREAD

**Issue by lauraghouzi** [20donkey/Term-project#7]
https://github.com/20donkey/Term-project/blob/7464e28bc485f94cf27b6f552c479bad7dcbde45/css/styles.css#L37

Throughout the website, the navigation bar/the top part is always a reddish color, then for Other and Contact it is yellow. I would suggest keeping everything consistent with the same color or changing it only for Contact so it stays consistent.

**Comment by 20donkey** [comment]
Actually, I changed the color for a purpose because I thought always the same color will be boring, but I will consider change it back to the same color as you mentioned. Thanks for your suggestion!
